export {PatrimonioRepository} from './patrimonio/patrimonio-repository'
export {LocalizacaoRepository} from './localizacao/localizacao-repository'
export {TipoPatrimonioRepository} from './tipo-patrimonio/tipo-patrimonio-repository'
export {ManutencaoRepository} from './manutencao/manutencao-repository'
export {ArquivoAnexadoRepository} from './arquivo-anexado/arquivo-anexado-repository'
export {UsuarioRepository} from './usuario/usuario-repository'